// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231013013759_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.Models.DiaModel", b =>
                {
                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("ValorDolar")
                        .HasColumnType("float");

                    b.Property<float>("ValorReal")
                        .HasColumnType("float");

                    b.HasKey("Data");

                    b.ToTable("Dias");
                });
#pragma warning restore 612, 618
        }
    }
}
